name: Test Application

on:
  push:
    branches:
      - main

jobs:
  check-tests:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check test scripts exist
        run: |
          if [ ! -f .tests/test.py ]; then
            echo "Test script not found." >&2
            echo "false" > napaka.txt
          else
            echo "true" > napaka.txt
          fi

      - name: Upload results as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: workflow-artifacts
          path: napaka.txt

  run-tests:
    needs: check-tests
    runs-on: self-hosted
    strategy:
      matrix:
        python-version: [3.8, 3.9]
    steps:
      - name: Download the workflow artifacts
        uses: actions/download-artifact@v4
        with:
          name: workflow-artifacts

      - name: Determine if tests should run
        run: |
          should_run_tests=$(cat napaka.txt)
          if [[ "$should_run_tests" != "true" ]]; then
            echo "Skipping tests due to errors."
            exit 78  # Exits with neutral status to skip the job
          fi

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: python -m unittest discover -s .tests
